### PR TITLE
Fix Provider verification and legacy security.txt

### LINKED ISSUE #44: Support legacy `security.txt` in domain root
According to RFC 9116, the `security.txt` file can also be placed under the top-level of the domain for legacy reasons. If both exist, the `/.well-known/security.txt` must be used. Should we handle this case?

_Originally posted by @KuechA in https://github.com/csaf-sbom/kotlin-csaf/pull/35#discussion_r1787402124_

### PR DESCRIPTION
**Pull request by milux**
- **Fixed verification to run after each Provider fetch**
- **Honor legacy security.txt location, fixes #44**

### CODE REVIEW

File: csaf-import/src/main/kotlin/io/github/csaf/sbom/retrieval/RetrievedProvider.kt [hunk 1]
```diff
@@ -99,20 +128,24 @@ class RetrievedProvider(val json: Provider, val role: Role) {
...
             val ctx = ValidationContext()
-            // Closure for providing HttpResponse to ValidationContext.
             // TODO: Only the last error will be available in result. We should do some logging.
             // First, we need to check if a .well-known URL exists.
             val wellKnownPath = "https://$domain/.well-known/csaf/provider-metadata.json"
             return loader
                 .fetchProvider(wellKnownPath, ctx)
-                .map { it.also { ctx.dataSource = ValidationContext.DataSource.WELL_KNOWN } }
+                .onSuccess { ctx.dataSource = ValidationContext.DataSource.WELL_KNOWN }
+                .mapCatching { p -> RetrievedProvider(p).also { it.validate(ctx) } }
```
Comment (oxisto) [inline csaf-import/src/main/kotlin/io/github/csaf/sbom/retrieval/RetrievedProvider.kt:137]: add this lambda to a variable and use it instead of having it three times?

File: csaf-validation/src/main/kotlin/io/github/csaf/sbom/validation/requirements/Requirements.kt [hunk 2]
```diff
@@ -51,7 +51,8 @@ object Requirement2ValidFilename : Requirement {
         val should = json.document.tracking.id.lowercase().replace("[^+\\-a-z0-9]+", "_") + ".json"
 
         // Extract filename out of response?
-        val filename = ctx.httpResponse?.request?.url?.pathSegments?.lastOrNull()
+        @Suppress("SimpleRedundantLet")
```
Comment (oxisto) [inline csaf-validation/src/main/kotlin/io/github/csaf/sbom/validation/requirements/Requirements.kt:54]: why is this necessary? is that a trick to get the coverage working?

**Review by oxisto — APPROVED** [review]
only minor things

File: csaf-import/src/main/kotlin/io/github/csaf/sbom/retrieval/RetrievedProvider.kt [hunk 3]
```diff
@@ -99,20 +128,24 @@ class RetrievedProvider(val json: Provider, val role: Role) {
             loader: CsafLoader = lazyLoader
         ): Result<RetrievedProvider> {
             val ctx = ValidationContext()
-            // Closure for providing HttpResponse to ValidationContext.
             // TODO: Only the last error will be available in result. We should do some logging.
             // First, we need to check if a .well-known URL exists.
             val wellKnownPath = "https://$domain/.well-known/csaf/provider-metadata.json"
```
Comment (oxisto) [inline csaf-import/src/main/kotlin/io/github/csaf/sbom/retrieval/RetrievedProvider.kt:133]: Can you please document the contents of https://github.com/csaf-sbom/kotlin-csaf/issues/48#issuecomment-2399612394 here

File: csaf-import/src/main/kotlin/io/github/csaf/sbom/retrieval/RetrievedProvider.kt (hunk 1 above)
Comment (milux) [reply csaf-import/src/main/kotlin/io/github/csaf/sbom/retrieval/RetrievedProvider.kt:137]: Not a big deal, but yes.

File: csaf-import/src/main/kotlin/io/github/csaf/sbom/retrieval/RetrievedProvider.kt (hunk 3 above)
Comment (milux) [reply csaf-import/src/main/kotlin/io/github/csaf/sbom/retrieval/RetrievedProvider.kt:147]: Done.
